config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :home, only: [:index], path: '/'
  
  resources :products, only: [:index, :show] do
  end

  resources :transactions, only: [], path: '/' do
    collection do
      get :cart
      post :cart
      match 'checkout(/:step)', :action => :checkout, :as => :checkout, via: [:get, :post]
      post :place_order
      get "order/:id/completed" => :completed, as: :completed
    end
  end

  root 'home#index'

  unless Rails.env.development?
    get "*any", via: :all, to: 'application#render_not_found'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :assetable, :polymorphic => true

  has_attached_file :attachment,
    :s3_credentials => 
      {
        :access_key_id      => ENV['AWS_ACCESS_KEY_ID'],
        :secret_access_key  => ENV['AWS_SECRET_ACCESS_KEY'],
        :bucket             => ENV['S3_BUCKET_NAME']
      },
    :s3_region    => ENV['S3_AWS_REGION'],
    :storage      => :s3,
    :s3_headers   => { "Cache-Control" => "max-age=31557600" },
    :s3_protocol  => ENV['S3_PROTOCOL'].present? ? ENV['S3_PROTOCOL'] : "http",
    :bucket       => ENV['S3_BUCKET_NAME'],
    :styles => {
        :mini     => "48x72>",
        :small    => "100x150>",
        :product  => "480x720>",
        :large    => "600x900>"
      },
    :default_style    => "product",
    :path             => "/:class/:id/:style/:basename.:extension",
    :default_url      => "/:class/:id/:style/:basename.:extension",
    :s3_host_alias    => ENV["S3_HOST_ALIAS"],
    :url              => ":s3_alias_url",
    :convert_options  => { all: '-strip -auto-orient -colorspace sRGB' }

  validates_attachment :attachment,
    :presence => true,
    :content_type => { :content_type => %w(image/jpeg image/jpg image/png image/gif) }
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
end

app/models/option_type.rb
class OptionType < ActiveRecord::Base
  validates :name, :uniqueness => true, :presence => true
  has_many :option_values, :class_name => "VariantOptionValue"
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :line_items
  
  belongs_to :bill_address, foreign_key: :bill_address_id, class_name: 'Address'
  alias_attribute :billing_address, :bill_address

  belongs_to :ship_address, foreign_key: :ship_address_id, class_name: 'Address'
  alias_attribute :shipping_address, :ship_address
end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug, use: :slugged

  has_many :variants
  has_many :images, :source => :images, :through => :variants

  validates :name, :presence => true
  validates :slug, :presence => true, :uniqueness => true
end

app/models/product_taxon.rb
class ProductTaxon < ActiveRecord::Base
  self.table_name = 'products_taxons'
  
  belongs_to :taxon
  belongs_to :product
end

app/models/taxon.rb
class Taxon < ActiveRecord::Base
  has_many :product_taxons, dependent: :destroy, inverse_of: :product
  has_many :products, :through => :product_taxons
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/models/variant.rb
class Variant < ActiveRecord::Base
  belongs_to :product
  has_many :images, :as => :assetable, :class_name => 'Asset'
  has_many :option_values, :class_name => "VariantOptionValue"

  def options_text
    option_values.map{|o| "#{o.option_type.presentation}: #{o.value.to_s.titleize}"}.join(' - ')
  end

  def in_stock?
    count_on_hand > 0
  end

  def discount?
    cost_price > price
  end

  def discount_amount
    cost_price - price
  end

  def display_price
    Money.new(price, ENV['CURRENCY']).format(symbol_after_without_space: true)
  end

  def display_cost_price
    Money.new(cost_price, ENV['CURRENCY']).format(symbol_after_without_space: true)
  end

  def discount_percent
    "#{((discount_amount * 100)/cost_price).round }%"
  end
end

app/models/variant_option_value.rb
class VariantOptionValue < ActiveRecord::Base
  belongs_to :option_type
  belongs_to :variant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :content_layout, :show_slider?, :hide_breadcrumbs?, :show_page_loading?

  rescue_from ActionController::InvalidCrossOriginRequest, :with => :render_error
  rescue_from ActiveRecord::RecordNotFound, :with => :render_not_found
  rescue_from ActionController::RoutingError, with: :render_not_found

  def render_not_found
    load_full_width_layout
    respond_to do |f| 
      f.html{ render :template => "errors/404", :status => 404 }
      f.js{ render :json => {:errors => '404 Not Found'}, :status => 404 }
    end
  end

  def render_error
    load_full_width_layout
    respond_to do |f| 
      f.html{ render :template => "errors/500", :status => 500 }
      f.js{ render :json => {:errors => '500 internal server error'}, :status => 500 }
    end
  end

  private
  def show_slider?
    params[:controller] == "home" && params[:action] == "index"
  end

  def show_page_loading?
    params[:controller] == "home" && params[:action] == "index"
  end

  def hide_breadcrumbs?
    ['home#index'].include?(page_id) || %w(transactions).include?(controller_name)
  end

  def collection?
    %w(index).include? params
  end

  def content_layout
    @content_layout ||= 'layouts/content_layouts/right_sidebar'
  end

  def page_id
    "#{controller_name}##{action_name}"
  end

  def load_full_width_layout
    @content_layout = 'layouts/content_layouts/full_width'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @hot_products = Product.limit(20)
    @products = Product.order("RANDOM()").limit(16)
  end

  private
    def content_layout
      @content_layout ||= 'layouts/content_layouts/full_width'
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_resource

  def index
  end

  def show
    @product = Product.friendly.find(params[:id])
    @product_related = Product.limit(10)
  end

  private
    def load_resource
      @title = @product_name
      if collection?
        @products = []
      else
        @product = []
      end   
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :load_resource
  before_action :ensure_checkout_steps, :only => [:checkout]

  def checkout
  end

  def place_order
  end

  def completed
  end

  private
  def load_resource
  end

  def content_layout
    @content_layout = 'layouts/content_layouts/full_width'
  end

  def ensure_checkout_steps
    params[:step] ||= 'login'
    redirect_to cart_transactions_path and return unless %w(login address payment).include?(params[:step])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def data_in_out
    %w(fade left right top bottom)
  end

  def original_url
    request.base_url + request.original_fullpath
  end

  def br(count)
    count.times.map{'<br/>'}.join('').html_safe
  end

  def highlight_products
    Product.order('id DESC').limit(10)
  end

  def default_currency
    ENV['CURRENCY'] || 'USD'
  end
end

app/views/addresses/_form.html.haml
- country_alpha = local_assigns.fetch :country_alpha, ENV['DEFAULT_COUNTRY']
- simple = local_assigns.fetch :simple, true
- country = Country[country_alpha] 

= f.fields_for address_type do |address_form|
  .form-group
    = address_form.label :address2, t('address.first_name_and_last_name')
    = address_form.text_field :first_name_and_last_name, :class => 'form-control', :data => {:v => "required", :em => t('validator.first_name_and_last_name'), :field => :first_name_and_last_name}
  .form-group
    = address_form.label :address2, t('address.address1')
    = address_form.text_field :address1, :class => 'form-control', :data => {:v => "required", :em => t('validator.address1'), :field => :address1}
  - unless simple
    .form-group
      = address_form.label :address2, t('address.address2')
      = address_form.text_field :address2, :class => 'form-control', :data => {:field => :address2}
  - if country == 'US'
    .form-group
      = address_form.label :address2, t('address.zipcode')
      = address_form.text_field :zipcode, :class => 'form-control', :data => {:v => "required", :em => t('validator.zipcode'), :field => :zipcode}
  .form-group
    = address_form.label :city, t('address.city')
    = address_form.text_field :city, :class => 'form-control', :data => {:v => "required", :em => t('validator.city'), :field => :city}
  .form-group
    = address_form.label :address2, t('address.state')
    = address_form.select :state, country.states.to_a.map{|s| [s[1]["name"], s[0]]}, :class => 'form-control', :data => {:v => "required", :em => t('validator.state'), :field => :state}
  - unless simple
    .form-group
      = address_form.label :address2, t('address.country')
    = address_form.select :country, ISO3166::Country.translations.to_a.map{|s| [s[1], s[0]]}, :selected => country_alpha, :class => 'form-control', :data => {:v => "required", :em => t('validator.country'), :field => :country}
  .form-group
    = address_form.label :address2, t('address.phone1')
    = address_form.text_field :phone1, :class => 'form-control', :data => {:v => "required", :em => t('validator.phone1'), :field => :phone1}
  - unless simple
    .form-group
      = address_form.label :address2, t('address.phone2')
    = address_form.text_field :phone2, :class => 'form-control', :data => {:field => :phone2}
  - if defined?(email)
    .form-group
      = address_form.label :address2, t('address.email')
      = address_form.text_field :email, :class => 'form-control', :data => {:v => "required email", :em => t('validator.email'), :field => :email}

app/views/home/details.html.haml
<h1>Products#details</h1>
<p>Find me in app/views/products/details.html.erb</p>

app/views/home/index.html.haml
= render 'shared/recommend_content'
#list-products
  .hr-title
    %span
      = fa_icon "list-ul"
      Danh sách sản phẩm
  .btn-group.pull-right{"aria-label" => "...", :role => "group"}
    %button.btn.btn-default.active{:type => "button"} Tất cả
    %button.btn.btn-default{:type => "button"} Áo sơ mi
    %button.btn.btn-default{:type => "button"} Áo thun
    %button.btn.btn-default{:type => "button"} Áo khoác
  .clearfix
  = render 'shared/list_products', :products => @products

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = [@title, ENV['PROJECT_NAME']].compact.join(' - ')
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag :modernizr
    = csrf_meta_tags
  %body
    = render 'shared/page_loading' if show_page_loading?
    = render 'shared/header'
    = render 'shared/slider' if show_slider?
    = render 'shared/breadcrumbs' unless hide_breadcrumbs?
    .container
      #main-content
        = render layout: content_layout do
          = yield
        = yield :extra_layout
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = yield :extra_js
    = render 'shared/footer'
    = render "shared/back_to_top"

app/views/layouts/content_layouts/_full_width.html.haml
.row
  .col-xs-12
    = yield

app/views/layouts/content_layouts/_left_sidebar.html.haml
.row
  .col-xs-12.col-sm-3
    - if content_for? :left_sidebar_content 
      = yield :left_sidebar_content
    - else
      = render 'shared/left_sidebar_content'
  .col-xs-12.col-sm-9
    = yield

app/views/layouts/content_layouts/_right_sidebar.html.haml
.row
  .col-xs-12.col-sm-9
    = yield
  .col-xs-12.col-sm-3
    - if content_for? :right_sidebar_content 
      = yield :right_sidebar_content
    - else
      = render 'shared/right_sidebar_content'

app/views/products/_related_products.html.haml
#product-items.owl-carousel
  - products.each do |product|
    = render "shared/product", :product => product

app/views/products/_variant_cart_form.html.haml
.product-name
  = product.name
  .brand
    by
    = link_to FFaker::Product.brand.titleize, '' 
.rating.init{"data-score" => "#{ rand(0.0..5.0)}"}
.stock-status
  = t('product.stock_status')
  - if variant.in_stock?
    %span.available
      = t('product.in_stock')
  - else
    %span.not-available
      = t('product.sold_out')
.clearfix
.description
  = variant.product.short_description.html_safe
.price
  - if variant.discount?
    .discount.margin-right-10
      = variant.display_cost_price
  = variant.display_price
.variants
  %select.select2.full-width{:name => "varaint_id"}
    - product.variants.each do |variant|
      %option{:value => "#{variant.id}"}
        = variant.options_text
%br/
.add-to-cart
  .quantity
    %select{:name => ""}
      %option{:value => "1"} 1
      %option{:value => "2"} 2
      %option{:value => "3"} 3
  %button.btn.btn-primary
    = t('product.add_to_cart')

app/views/products/show.html.haml
- variant_default = @product.variants.first
%h1.page-title
  = @product.name
.product-details-page.row
  .col-xs-5
    .main-image
      - if variant_default.discount?
        .save-off-banner
          .wrap-banner
            = image_tag('save-off.png')
            .text-off
              = variant_default.discount_percent
      - image = variant_default.images.first
      - large_image_url = image ? image.attachment(:large) : image_url("noimage/large.png")
      = image_tag large_image_url, class: "img-responsive img-main-image", "data-zoom-image" => large_image_url
      %a.fancybox{:href => ""}
      %a.fancybox.expand-image{:href => large_image_url, :rel => "gallery1", :title => @product.name}
        %span.fa.fa-expand
    .thumbnails.owl-carousel
      - variant_default.images.each do |image|
        = link_to 'javascript:void(0);', "data-source" => image.attachment(:product), class: 'thumbnail-item' do
          = image_tag image.attachment(:small), class: 'image'
  .col-xs-7
    = render 'variant_cart_form', :product => @product, :variant => variant_default

= br(2)
%ul#product_details_tab.nav.nav-tabs{:role => "tablist"}
  %li.active{:role => "presentation"}
    %a{"aria-controls" => "review", "data-toggle" => "tab", :href => "#tab_details", :role => "tab"}= t('product.details')
  %li{:role => "presentation"}
    %a{"aria-controls" => "images", "data-toggle" => "tab", :href => "#tab_comments", :role => "tab"}= t('product.customer_comment')

#product_details_tab_content.tab-content
  #tab_details.tab-pane.active{:role => "tabpanel"} 
    = @product.description.html_safe.present? ? @product.description.html_safe : @product.short_description.html_safe
  #tab_comments.tab-pane{:role => "tabpanel"}
    .fb-comments{"data-colorscheme" => "light", "data-href" => "#{ original_url }", "data-numposts" => "5", "data-width" => "100%", "data-mobile" => "true", "data-order-by" => "time"}



= content_for :extra_layout do
  .clearfix
  = br(4)
  #related-products
    .hr-title
      %span
        = fa_icon "link"
        = t('product.related')
    = render 'related_products', :products => @product_related

= content_for :extra_js do
  :javascript
    $(document).ready(function(){
      $('#product_details_tab a:first').tab('show')
      
      setTimeout(function(){
        (function(d, s, id) {
          console.log('load')
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.3&appId=1434833363500454";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
      }, 300000)
    })

app/views/shared/_back_to_top.html.haml
#scroll_to_top
  = fa_icon "chevron-up"

app/views/shared/_breadcrumbs.html.haml
.container
  %ol.breadcrumb
    %li
      %a{:href => "#"} Home
    %li
      %a{:href => "#"} Link
    %li.active 
      Current

app/views/shared/_footer.html.haml
#footer
  .hr-title
    %span
      = image_tag "logo.png"
  .social-media
    %a.facebook{:href => "#"}
      = fa_icon "facebook"
    %a.twitter{:href => "#"}
      = fa_icon "twitter"
    %a.google{:href => "#"}
      = fa_icon "google"
  #copyright
    &copy
    %a{:href => "#"}
      HD Shop
    2015
    %p
      All Rights Reserved. Design by
      %a{:href => "http://portfolio.hiepdinh.com"}
        Hiep Dinh.
  #company-info
    %p
      = fa_icon "building"
      167 Chấn Hưng, Phường 6, Tân Bình, Hồ Chí Minh
    %p
      = fa_icon "phone"
      (84) 128-528-6828 hoặc (08) 733-0013
    %p
      = fa_icon "clock-o"
      Thứ 2 - Thứ 6: 8.00 - 17.00, Thứ 7 - CN: 8.00 - 14.00
  #map


%script{:src => "//maps.googleapis.com/maps/api/js?v=3.exp", :type => "text/javascript"}
:javascript
  function map_footer_initialize() {
    var myLatlng = new google.maps.LatLng(21.0333, 105.8500);
    var mapOptions = {
      zoom: 16,
      center: myLatlng
    }
    var map = new google.maps.Map(document.getElementById('map'), mapOptions);

    var marker = new google.maps.Marker({
        position: myLatlng,
        map: map,
        title: 'Hello World!'
    });
  }

  $(function(){
    var map_footer = new Waypoint({
      element: $('#footer'),
      handler: function(direction) {
        if(direction == "down"){
          console.log('Loading map');
          map_footer_initialize();
          this.destroy()
        }
      },
      offset: '100%'
    })
  });




app/views/shared/_header.haml
#header
  #top_bar
    .greeting.pull-left
      = t('header.getting')
    %ul#top-bar-links.pull-right
      %li
        %a{:href => ""}
          = fa_icon "shopping-cart"
          &nbsp;
          = t('header.cart')
      %li
        %a{:href => ""}
          = fa_icon "user"
          &nbsp;
          = t('header.login')
  #main-menu
    .top
      .row
        .col-xs-12.col-md-4.col-sm-4{style: "padding-left: 0px"}
          %form#search_form{:role => "search", action: "/abc", method: :post}
            = fa_icon "search", class: "search-logo", onclick: "search_form.submit()"      
            %input{:placeholder => t('menu.search_place_holder'), :type => "text"}/
        .col-xs-12.col-md-4.col-sm-4
          %a.logo{:href => "/"}
            = image_tag "logo.png", class: "logo"
        .col-xs-12.col-md-4.col-sm-4
          = render '/shared/mini_cart'
    .bottom
      .col-xs-12
        %ul#menu-links
          %li.active
            = link_to "Trang Chủ", root_path
          %li
            = link_to "Sản phẩm", products_path
          %li
            %a{:href => "#"}
              Liên hệ
          %li
            %a{:href => "#"}
              Về chúng tôi

app/views/shared/_left_sidebar_content.html.haml
%h1.page-title.double
  Nổi bật
%ul.mini-products.row
  - 10.times do
    - product_discount = [true, false].sample
    - product_new = [true, false].sample
    %li.mini-product.col-xs-12.col-md-12
      .left-column
        = link_to "/products/#{ FFaker::Name.name.humanize }", class: 'thumb' do
          = image_tag 'mini-products/1.jpg'
      .right-column
        .name
          = FFaker::Name.name
        .rating.init{"data-score" => "#{ rand(0.0..5.0)}"}
        .price
          - if product_discount
            .discount
              = "#{ rand(100..999) }K"
          = "#{ rand(100..999) }K"

app/views/shared/_main_content.html.haml
#main-content
  .title
    = fa_icon "list-ul"
    %span
      Danh sách sản phẩm


app/views/shared/_mini_cart.html.haml
#mini-cart
  .status
    %a{:href => "/cart"}
      = fa_icon "shopping-cart"
      .total-quantity
        2
    .cart-dropdown
      %a.fa.fa-times.close-button{:href => "javascript:void(0)"}
      %table.table.table-bordered.mini-cart-items
        - 3.times do 
          %tr
            %td{style: "width: 87px"}
              .thumb
                .quantity= rand(1..99)
                = image_tag "product-thumb.jpg"
            %td.product-info
              %a.name{:href => "/"}
                Máy ảnh Canon 5D
            %td
              = "#{rand(99..150)}K"
            %td
              .action
                %a.remove{:href => "javascript:void(0);"}
                  = fa_icon "trash"
        %tr.footer-info
          %td.title{:colspan => 2}
            = t('cart.subtotal')
          %td
            %span 300K
      .cart-action.padding-bottom-5
        %a.button-checkout.btn{:href => "/checkout"}
          = fa_icon "shopping-cart" 
          %span.margin-left-5= t('header.cart').upcase

app/views/shared/_page_loading.html.haml
#page_loading
  %h1.logo
    = image_tag "logo.png"
  %div.spin    
    .icon-spin
      = image_tag('loading.gif', style: 'width: 60px; height: 60px')
      =# fa_icon "spinner spin"

app/views/shared/_product.html.haml
- variant = product.variants.first
- product_url = product_path(product)
%div.product-item.wow.fadeInUp
  .product-image
    - if variant.discount?
      .save-off-banner
        .wrap-banner
          = image_tag('save-off.png')
          .text-off
            = variant.discount_percent
    - image = variant.images.first
    - product_image_url = image ? image.attachment(:product) : image_path("noimage/product.png")
    - large_image_url = image ? image.attachment(:large) : image_path("noimage/large.png")
    = link_to '', product_url, class: "black-layer"
    = link_to fa_icon("search-plus"), large_image_url, class: 'fancybox fancybox-zoom'
    .nav-bar
      .row
        = link_to product_url, class: "quick-view" do
          .col-sm-6.center-block
            XEM NHANH
        %a.add-to-cart{:href => "javascript:void(0)"}
          .col-sm-6.center-block
            THÊM VÀO GIỎ
    = image_tag product_image_url, class: 'product_photo'
  .caption
    %a.categories{:href => "/categories/"}
      = FFaker::Product.brand.titleize
    %a.name{:href => product_url}
      = product.name.size < 23 ? product.name : "#{product.name[0..20]} ..."
    .rating.init{"data-score" => "#{ rand(0.0..5.0)}"}
    .price
      - if variant.discount?
        .discount
          = variant.display_cost_price
      = variant.display_price

app/views/shared/_recommend_content.html.haml
#recommend-product
  .hr-title
    %span
      = fa_icon "star"
      Sản phẩm nổi bật

  #product-items.owl-carousel
    - @hot_products.each do |product|
      = render "shared/product", :product => product

app/views/shared/_right_sidebar_content.html.haml
%h1.page-title.double
  = t('g.highlight')
%ul.mini-products.row
  - highlight_products.each do |product|
    - variant = product.variants.first
    - image = variant.images.first
    - product_url = product_path(product)
    %li.mini-product.col-xs-12.col-md-12
      .left-column
        - mini_image_url = image ? image.attachment(:small) : image_url("noimage/mini.png")
        = link_to product_url, class: 'thumb' do
          = image_tag mini_image_url
      .right-column
        .name
          = link_to truncate(product.name, length: 25, omission: ' ...'), product_url
        .rating.init{"data-score" => "#{ rand(0.0..5.0)}"}
        .price
          - if variant.discount?
            .discount
              = variant.display_cost_price
          = variant.display_price

app/views/transactions/_order_summary.html.haml
- line_items = local_assigns.fetch :line_items, :true
- editable = local_assigns.fetch :editable, :true

.form-wrapper.address
  %h1.page-title.s18x.no-space
    = t('checkout.order_address')
  %p.margin-bottom-10 ĐINH HOÀNG HIỆP
  %div 13C/KA Đường Vào Ga - Hưng Long
  %div Đồng Nai - Huyện Trảng Bom
  %div Điện thoại di động: 01285286828

.checkout_mini_cart.order-details.padding-bottom-0.form-wrapper
  %h1.page-title.s18x.no-space
    = t('checkout.order_summary')
  .no-space
    %table.table
      - if line_items
        %thead
          %tr
            %th.product-name
              = t('g.product')
            %th.quantity
              = t('g.quantity')
            %th.price
              = t('g.price')
      %tbody
        - if line_items
          = render 'transactions/table_line_items', :order => @order, :editable => editable
        %tr.shipping-cost
          %td.title Phí vận chuyển
          %td.value.text-right{:colspan => 2, :style => 'vertical-align: middle;'} Miễn phí
        %tr.payment-method
          %td.title Thanh toán
          %td.value.text-right{:colspan => 2, :style => 'vertical-align: middle; min-width: 193px;'} Thanh toán khi nhận hàng
        %tr.subtotal
          %td.title
            = t('cart.subtotal')
            .vat_des
              = "(#{t('cart.include_vat')})"
          %td.value{:colspan => 2} 906.000 VND

app/views/transactions/cart.html.haml
.row
  .col-md-7
    .form-wrapper
      %h1.page-title.s18x.no-space
        = t('header.cart')
      = form_for cart_transactions_path, html: { id: "cart_page" } do
        .no-space
          %table.table
            %thead
              %tr
                %th= t('cart.image')
                %th= t('product.name') 
                %th= t('product.price')
                %th{:style => "width: 90px;"}= t('cart.quantity')
                %th= t('cart.subtotal')
                %th= t('cart.remove')
            %tbody
              - 5.times do
                %tr
                  %td
                    = link_to product_path(1) do
                      = image_tag 'mini-products/1.jpg', size: '55x55'
                  %td{ style: 'text-align: left;'}
                    = link_to "Integer consequat ante lectus", product_path(1)
                  %td
                    50,000 VND
                  %td
                    %select.select2.no-search{:name => ""}
                      %option{:value => "1"} 1
                      %option{:value => "1"} 2
                      %option{:value => "1"} 3
                  %td
                    50,000 VND
                  %td
                    %a.remove-form-cart{:href => "javascript:void(0)"}
                      %i.fa.fa-trash
    .cart-action
      %a.button-default.pull-left{href: "/"}
        = fa_icon 'shopping-cart', :class => 'left'
        = t('cart.continue_shopping').upcase
  .col-md-5
    = render 'transactions/order_summary', :line_items => false
    %a.button-default.full-block.pull-right{:href => "/checkout"}
      = fa_icon 'check', :class => 'left'
      = t('cart.process_checkout').upcase

app/views/transactions/checkout.html.haml
= render 'steps', :step_name => params[:step]

.row.margin-top-20
  .col-xs-12.col-sm-7
    = form_for :order, url: checkout_transactions_path(:payment), :html => {:class => 'checkout-form form-wrapper'} do |f|
      .padding-bottom-20
        = render "transactions/steps/#{params[:step]}", :f => f
      .clearfix
      %hr.margin-top-0
      %button.button-default.pull-right.submit-checkout
        = "#{t("checkout.next_#{params[:step]}").upcase}"
        %span.arrow-right.fa.fa-angle-right
      .clearfix
  .col-xs-12.col-sm-5
    = render 'order_summary'

app/views/transactions/steps/_address.html.haml
%h1.page-title.s18x.no-space
  = t('checkout.address')
#shiping_address_area
  = render 'addresses/form', :f => f, :address_type => :ship_address_attributes